name: release

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Tag name
      id: tag_name
      run: |
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

    - name: Update apt
      run: |
        sudo apt update

    - name: Install wine
      run: |
        sudo apt install wine64
        sudo ln -sf /usr/bin/wine /usr/bin/wine64
        which wine || true
        which wine64 || true

    - name: Install dependencies
      run: yarn install

    - name: Build package
      run: yarn package

    - name: Zip package
      run: |
        zip -r over-the-top-${{ steps.tag_name.outputs.SOURCE_TAG }}-win.zip out/over-the-top-win32-x64
        zip -r over-the-top-${{ steps.tag_name.outputs.SOURCE_TAG }}-linux.zip out/over-the-top-linux-x64
        zip -r over-the-top-${{ steps.tag_name.outputs.SOURCE_TAG }}-mac.zip out/over-the-top-darwin-x64

    - name: Create a Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}

    - name: Upload Windows Release Zip
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./over-the-top-${{ steps.tag_name.outputs.SOURCE_TAG }}-win.zip
        asset_name: over-the-top-${{ steps.tag_name.outputs.SOURCE_TAG }}-win.zip
        asset_content_type: application/zip

    - name: Upload Linux Release Zip
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./over-the-top-${{ steps.tag_name.outputs.SOURCE_TAG }}-linux.zip
        asset_name: over-the-top-${{ steps.tag_name.outputs.SOURCE_TAG }}-linux.zip
        asset_content_type: application/zip

    - name: Upload Mac Release Zip
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./over-the-top-${{ steps.tag_name.outputs.SOURCE_TAG }}-mac.zip
        asset_name: over-the-top-${{ steps.tag_name.outputs.SOURCE_TAG }}-mac.zip
        asset_content_type: application/zip

