name: release

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install wine
      run: |
        sudo apt install wine64

    - name: Install dependencies
      run: yarn install

    - name: Build package
      run: yarn package

    - name: Zip package
      run: |
        zip -r over-the-top-${{github.ref}}-win.zip out/over-the-top-win32-x64
        zip -r over-the-top-${{github.ref}}-linux.zip out/over-the-top-linux-x64
        zip -r over-the-top-${{github.ref}}-mac.zip out/over-the-top-darwin-x64

    - name: Create a Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}

    - name: Upload Windows Release Zip
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./over-the-top-${{github.ref}}-win.zip
        asset_name: over-the-top-${{github.ref}}-win.zip
        asset_content_type: application/zip

    - name: Upload Linux Release Zip
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./over-the-top-${{github.ref}}-linux.zip
        asset_name: over-the-top-${{github.ref}}-linux.zip
        asset_content_type: application/zip

    - name: Upload Mac Release Zip
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./over-the-top-${{github.ref}}-mac.zip
        asset_name: over-the-top-${{github.ref}}-mac.zip
        asset_content_type: application/zip

